### ISSUE TITLE
Don't share the same APPID

### ISSUE THREAD

**Issue by titsuki** [palapitta/Weather#2]
Hi 

The following page http://openweathermap.org/appid says that
”APPID {APIKEY} is **your unique** API key”

I think that you should write the explanation of how to get your own APPID.

**Comment by palapitta** [comment]
using that key is not a problem .
updated readme file to get a free unique api key

**Comment by titsuki** [comment]
> using that key is not a problem .

hmm, if a user using your APPID violates the terms of use you will shoulder the responsibility.
So I strongly recommend you to delete the following line
https://github.com/palapitta/Weather/blob/master/lib/Weather.pm6#L6

**Comment by palapitta** [comment]
after watching the comment i changed the files not seeing the PR .
sending apikey at initialization is good idea , change the file again and send me PR and i will merge it

**Comment by titsuki** [comment]
@palapitta 
I have fixed the conflicts. :)
